# Install and Run Nginx in Node-1 server
- name: Install Nginx in Node-1
  hosts: web
  become: yes
  tasks:
  - name: Install Nginx
    ansible.builtin.package:
      name: nginx
      state: present
  - name: Start Service
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes
