# Variables
# Local no need username and password
# ansible-playbook -i inventory.ini  04-vars.yaml
- name: Play Level Variables
  hosts: local
  connection: local # No need to provide username & password
  vars: 
    COURSE: "DevOps wth AWS"
    DURATION: "140Hrs"
    TRAINER: "Siva Kumar Anna"
  tasks:
  - name: Print Variables
    vars:
      COURSE: Ansible
    ansible.builtin.debug:
      msg: "Course is: {{ COURSE }}, Trainer is: {{ TRAINER }}, "


     