# Access File Variables
# ansible-playbook -i inventory.ini  06-file-vars.yaml
- name: File Level Variables
  hosts: local
  connection: local
  vars_files:
  - course.yaml
  tasks:
  - name: Print Variables
    vars:
      COURSE: Ansible
    ansible.builtin.debug:
      msg: "Course is: {{ COURSE }}, Trainer is: {{ TRAINER }}, "
