# Argument Level Variable
# ansible-playbook -i inventory.ini -e Name=VinodP 09-args-vars.yaml
- name: Args Level Variables
  hosts: local
  connection: local
  tasks:
    - name: Print variables from args
      ansible.builtin.debug:
        msg: "Hi {{ Name }}, Good Morning"