- name: demo on conditions
  hosts: local
  connection: local
  vars:
    is_live: true
  tasks:
  - name: Check Live or Not
    ansible.builtin.debug:
      msg: "Yes, it is live {{ is_live }}"
    when: is_live