- name: Check a number less than 10 or not 
  hosts: local
  connection: local
  vars:
    number_of_sessions: 7
  tasks:
  - name: is ansible more than 5 sessions
    ansible.builtin.debug:
      msg: "Yes, the sessions is more than 5"
    when: number_of_sessions > 5