- name: Install Packages
  hosts: local
  connection: local
  become: yes # Root User
  tasks:
  - name: Install packages
    ansible.builtin.package:
      name: "{{ item.name }}"
      state: "{{ item.state }}"
    loop:
    - {name: mysql, state: "absent"}
    - {name: nginx, state: "present"}
    - {name: zip, state: "present"}